version: '3.7'

 

services:
  server:
    image: seatsurfing/backend
    restart: always
    networks:
      sql:
      http:
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: 'postgres://seatsurfing:DB_PASSWORD@db/seatsurfing?sslmode=disable'
      JWT_SIGNING_KEY: 'some_random_string'
      BOOKING_UI_BACKEND: 'booking-ui:3001'
      ADMIN_UI_BACKEND: 'admin-ui:3000'
      PUBLIC_URL: 'https://localhost:8080/ui/search'
      FRONTEND_URL: 'https://localhost:8080/ui/search'
  booking-ui:
    image: aamarebdg/booking-ui-bdg:v1
    restart: always
    networks:
      http:
    environment:
      FRONTEND_URL: 'https://localhost:8080/ui/search'
  admin-ui:
    image: aamarebdg/admin-ui-bdg:local
    restart: always
    networks:
      http:
    environment:
      FRONTEND_URL: 'http://localhost:8080/admin/dashboard/'
  db:
    image: postgres:12
    restart: always
    networks:
      sql:
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

 

volumes:
  db:

 

networks:
  sql:
  http: